version: '3.4'

services:
  nginx:
    image: nginx:1.21.6
    volumes:
      - ./nginx:/tmp/nginx
    environment:
      - FLASK_SERVER_ADDR=backend:5001
    command: /bin/bash -c "envsubst < /tmp/nginx/default.conf > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'" 
    ports:
      - 80:80
      - 443:443
    depends_on:
      - backend

  backend:
    image: app-flask
    build:
      context: ./app-flask
      dockerfile: ./Dockerfile
      args:
        HOST_UID: $MYUID
    container_name: flask_container
    ports:
      - 5001:5001
    working_dir: /app
    volumes:
      - ./app-flask:/app
  
  music-api:
    image: music-api-image
    build:
      context: ./music-api-php
      dockerfile: ./Dockerfile
    container_name: music_api_container
    ports:
      - 5002:80

  nodejs-server:
    image: nodejs-server-image
    build:
      context: ./nodejs-server
      dockerfile: ./Dockerfile
    environment:
      - METING_SERVER_ADDR=http://music-api
    container_name: nodejs_server_container
    ports:
      - 5003:3000
    depends_on:
      - music-api
  

