version: '3.4'

services:
  nginx:
    image: nginx:1.21.6
    volumes:
      - ./nginx:/tmp/nginx
    environment: 
      - FLASK_SERVER_ADDR=backend:5001
    command: /bin/bash -c "envsubst < /tmp/nginx/default.conf > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'" 
    ports:
      - 80:80
      - 443:443
    depends_on:
      - backend

  backend:
    image: app-flask
    build:
      context: ./app-flask
      dockerfile: ./Dockerfile
      args:
        HOST_UID: $MYUID
    container_name: flask_container
    ports:
      - 5001:5001
    working_dir: /app
    volumes:
      - ./app-flask:/app
  

