name: APP AUTO DEPLOY

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.12.0'    
        
    - name: Build web
      run: cd app-vue3 && npm install && npm run build
    
    - name: Deploy APP
      env:
        KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        HOST: ${{ secrets.REMOTE_HOST }}
        USER: ${{ secrets.REMOTE_USER }}
        SSL_KEY: ${{ secrets.SSL_KEY }}
        SSL_PEM: ${{ secrets.SSL_PEM }}
      run: |
        mkdir -p ~/.ssh/ && echo "$KEY" > ~/.ssh/id_rsa && chmod 600 ~/.ssh/id_rsa
        echo ${SSL_KEY} > nginx/xcya.key && echo ${SSL_PEM} > nginx/xcya.pem
        ssh -o StrictHostKeyChecking=no ${USER}@${HOST} "rm -rf ~/media-hotchpotch && docker rmi $(docker images | grep "none" | awk '{print $3}')"
        scp -o StrictHostKeyChecking=no -r ./ ${USER}@${HOST}:~/media-hotchpotch
        ssh -o StrictHostKeyChecking=no ${USER}@${HOST} "docker compose up -d --build"
        
